import type { ConnectorCatalogItem } from "@/lib/connectors/connector-types";

export const connectorCatalog: ConnectorCatalogItem[] = [
  {
    id: "gmail",
    name: "Gmail",
    category: "communication",
    description: "Send and receive business email through your digital workforce.",
    capabilities: ["Inbound mail routing", "Outbound replies", "Thread summaries"],
    permissions: ["Read mail", "Send mail", "Manage labels"],
    usedBySpecialists: ["Customer Service Specialist", "Sales Specialist"],
    usedByTeams: ["Dental Clinic Team", "General Business Team"],
    requiredFor: ["Email automation", "Client follow-ups"],
    relatedConnectors: ["google-calendar", "google-drive"],
    recommendedWorkflows: ["Inbox triage", "Client follow-up sequences"],
    provider: "Google",
    mockProvider: true,
    logoColor: "#EA4335",
    logoInitials: "GM",
  },
  {
    id: "outlook",
    name: "Outlook",
    category: "communication",
    description: "Microsoft email for teams on Microsoft 365.",
    capabilities: ["Mailbox sync", "Calendar invites", "Shared inbox support"],
    permissions: ["Read mail", "Send mail", "Calendar read"],
    usedBySpecialists: ["Customer Service Specialist"],
    usedByTeams: ["Legal Office Team"],
    requiredFor: ["Microsoft-based communication"],
    relatedConnectors: ["outlook-calendar"],
    recommendedWorkflows: ["Shared inbox routing"],
    provider: "Microsoft",
    mockProvider: false,
    logoColor: "#0078D4",
    logoInitials: "OL",
  },
  {
    id: "whatsapp",
    name: "WhatsApp Business",
    category: "communication",
    description: "Business messaging for customer conversations.",
    capabilities: ["Message routing", "Template replies", "Conversation handoff"],
    permissions: ["Send messages", "Read conversations", "Manage templates"],
    usedBySpecialists: ["Customer Service Specialist"],
    usedByTeams: ["Dental Clinic Team", "Restaurant Team"],
    requiredFor: ["WhatsApp customer support"],
    relatedConnectors: ["gmail", "hubspot"],
    recommendedWorkflows: ["WhatsApp auto-reply", "Appointment confirmations"],
    provider: "Meta",
    mockProvider: true,
    logoColor: "#25D366",
    logoInitials: "WA",
  },
  {
    id: "telegram",
    name: "Telegram",
    category: "communication",
    description: "Lightweight messaging for support and notifications.",
    capabilities: ["Bot messaging", "Group notifications"],
    permissions: ["Send messages", "Read updates"],
    usedBySpecialists: ["Customer Service Specialist"],
    usedByTeams: [],
    requiredFor: ["Telegram-based support"],
    relatedConnectors: [],
    recommendedWorkflows: ["Alert notifications"],
    provider: "Telegram",
    mockProvider: false,
    logoColor: "#26A5E4",
    logoInitials: "TG",
  },
  {
    id: "slack",
    name: "Slack",
    category: "communication",
    description: "Team communication and operational alerts.",
    capabilities: ["Channel notifications", "Escalation routing"],
    permissions: ["Post messages", "Read channels"],
    usedBySpecialists: ["Workflow Specialist"],
    usedByTeams: ["General Business Team"],
    requiredFor: ["Internal team alerts"],
    relatedConnectors: ["github", "vercel"],
    recommendedWorkflows: ["Escalation alerts"],
    provider: "Slack",
    mockProvider: false,
    logoColor: "#4A154B",
    logoInitials: "SL",
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    category: "communication",
    description: "Enterprise messaging and meeting coordination.",
    capabilities: ["Chat routing", "Meeting notifications"],
    permissions: ["Send messages", "Read teams"],
    usedBySpecialists: ["Customer Service Specialist"],
    usedByTeams: [],
    requiredFor: ["Microsoft Teams workflows"],
    relatedConnectors: ["outlook"],
    recommendedWorkflows: ["Internal ops notifications"],
    provider: "Microsoft",
    mockProvider: false,
    logoColor: "#6264A7",
    logoInitials: "MS",
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    category: "scheduling",
    description: "Appointment scheduling and calendar automation.",
    capabilities: ["Book appointments", "Reschedule events", "Send reminders"],
    permissions: ["Read calendar", "Create events", "Update events"],
    usedBySpecialists: ["Scheduling Specialist"],
    usedByTeams: ["Dental Clinic Team", "Restaurant Team", "Flight School Team"],
    requiredFor: ["Appointment automation", "Calendar management"],
    relatedConnectors: ["gmail", "whatsapp"],
    recommendedWorkflows: ["Appointment booking", "No-show follow-up"],
    provider: "Google",
    mockProvider: true,
    logoColor: "#4285F4",
    logoInitials: "GC",
  },
  {
    id: "outlook-calendar",
    name: "Outlook Calendar",
    category: "scheduling",
    description: "Microsoft calendar for scheduling workflows.",
    capabilities: ["Event creation", "Availability checks"],
    permissions: ["Read calendar", "Manage events"],
    usedBySpecialists: ["Scheduling Specialist"],
    usedByTeams: ["Legal Office Team"],
    requiredFor: ["Microsoft scheduling workflows"],
    relatedConnectors: ["outlook"],
    recommendedWorkflows: ["Meeting scheduling"],
    provider: "Microsoft",
    mockProvider: false,
    logoColor: "#0078D4",
    logoInitials: "OC",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    description: "Online payments, invoicing, and billing automation.",
    capabilities: ["Payment processing", "Invoice generation", "Subscription tracking"],
    permissions: ["Read transactions", "Create invoices", "View customers"],
    usedBySpecialists: ["Finance Specialist"],
    usedByTeams: ["Dental Clinic Team"],
    requiredFor: ["Online payments", "Billing automation"],
    relatedConnectors: ["quickbooks", "hubspot"],
    recommendedWorkflows: ["Invoice follow-up", "Payment reminders"],
    provider: "Stripe",
    mockProvider: true,
    logoColor: "#635BFF",
    logoInitials: "ST",
  },
  {
    id: "square",
    name: "Square",
    category: "payments",
    description: "In-person and online payment processing.",
    capabilities: ["POS sync", "Payment tracking"],
    permissions: ["Read payments", "View customers"],
    usedBySpecialists: ["Finance Specialist"],
    usedByTeams: ["Restaurant Team", "Retail Team"],
    requiredFor: ["Retail payment workflows"],
    relatedConnectors: ["stripe"],
    recommendedWorkflows: ["Daily sales reconciliation"],
    provider: "Square",
    mockProvider: false,
    logoColor: "#006AFF",
    logoInitials: "SQ",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "crm",
    description: "CRM, pipeline tracking, and lead management.",
    capabilities: ["Contact sync", "Deal tracking", "Pipeline updates"],
    permissions: ["Read contacts", "Update deals", "View pipeline"],
    usedBySpecialists: ["Sales Specialist", "Customer Service Specialist"],
    usedByTeams: ["General Business Team"],
    requiredFor: ["CRM automation", "Lead nurturing"],
    relatedConnectors: ["gmail", "stripe"],
    recommendedWorkflows: ["Lead follow-up", "Pipeline updates"],
    provider: "HubSpot",
    mockProvider: true,
    logoColor: "#FF7A59",
    logoInitials: "HS",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    category: "crm",
    description: "Enterprise CRM and sales operations.",
    capabilities: ["Account sync", "Opportunity tracking"],
    permissions: ["Read accounts", "Update opportunities"],
    usedBySpecialists: ["Sales Specialist"],
    usedByTeams: [],
    requiredFor: ["Enterprise CRM workflows"],
    relatedConnectors: ["hubspot"],
    recommendedWorkflows: ["Sales pipeline automation"],
    provider: "Salesforce",
    mockProvider: false,
    logoColor: "#00A1E0",
    logoInitials: "SF",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    category: "crm",
    description: "Sales pipeline management for growing teams.",
    capabilities: ["Deal tracking", "Activity logging"],
    permissions: ["Read deals", "Update activities"],
    usedBySpecialists: ["Sales Specialist"],
    usedByTeams: [],
    requiredFor: ["Pipeline automation"],
    relatedConnectors: ["hubspot"],
    recommendedWorkflows: ["Deal stage updates"],
    provider: "Pipedrive",
    mockProvider: false,
    logoColor: "#017737",
    logoInitials: "PD",
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    category: "accounting",
    description: "Accounting and financial record keeping.",
    capabilities: ["Invoice sync", "Expense tracking"],
    permissions: ["Read invoices", "View accounts"],
    usedBySpecialists: ["Finance Specialist"],
    usedByTeams: ["Dental Clinic Team"],
    requiredFor: ["Accounting reconciliation"],
    relatedConnectors: ["stripe", "xero"],
    recommendedWorkflows: ["Monthly reconciliation"],
    provider: "Intuit",
    mockProvider: false,
    logoColor: "#2CA01C",
    logoInitials: "QB",
  },
  {
    id: "xero",
    name: "Xero",
    category: "accounting",
    description: "Cloud accounting for small businesses.",
    capabilities: ["Bank reconciliation", "Invoice management"],
    permissions: ["Read transactions", "View invoices"],
    usedBySpecialists: ["Finance Specialist"],
    usedByTeams: [],
    requiredFor: ["Xero-based accounting"],
    relatedConnectors: ["stripe"],
    recommendedWorkflows: ["Invoice matching"],
    provider: "Xero",
    mockProvider: false,
    logoColor: "#13B5EA",
    logoInitials: "XR",
  },
  {
    id: "github",
    name: "GitHub",
    category: "development",
    description: "Code repositories, issues, and deployment triggers.",
    capabilities: ["Repo monitoring", "PR notifications", "Action triggers"],
    permissions: ["Read repositories", "View actions"],
    usedBySpecialists: ["Workflow Specialist"],
    usedByTeams: [],
    requiredFor: ["Development workflow automation"],
    relatedConnectors: ["vercel", "slack"],
    recommendedWorkflows: ["Deploy notifications", "Issue triage"],
    provider: "GitHub",
    mockProvider: true,
    logoColor: "#24292F",
    logoInitials: "GH",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "development",
    description: "Deployment monitoring and release automation.",
    capabilities: ["Deploy status", "Preview URLs", "Build notifications"],
    permissions: ["Read deployments", "View projects"],
    usedBySpecialists: ["Workflow Specialist"],
    usedByTeams: [],
    requiredFor: ["Deployment automation"],
    relatedConnectors: ["github"],
    recommendedWorkflows: ["Deploy success alerts"],
    provider: "Vercel",
    mockProvider: true,
    logoColor: "#FFFFFF",
    logoInitials: "VC",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "development",
    description: "Database and backend service monitoring.",
    capabilities: ["Database health", "Auth event monitoring"],
    permissions: ["Read project status"],
    usedBySpecialists: ["Workflow Specialist"],
    usedByTeams: [],
    requiredFor: ["Backend monitoring"],
    relatedConnectors: ["vercel", "github"],
    recommendedWorkflows: ["Database alert routing"],
    provider: "Supabase",
    mockProvider: false,
    logoColor: "#3ECF8E",
    logoInitials: "SB",
  },
  {
    id: "google-drive",
    name: "Google Drive",
    category: "storage",
    description: "Document storage and file sharing.",
    capabilities: ["File retrieval", "Document sharing"],
    permissions: ["Read files", "Upload files"],
    usedBySpecialists: ["Customer Service Specialist"],
    usedByTeams: [],
    requiredFor: ["Document workflows"],
    relatedConnectors: ["gmail", "google-calendar"],
    recommendedWorkflows: ["Document delivery"],
    provider: "Google",
    mockProvider: false,
    logoColor: "#4285F4",
    logoInitials: "GD",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    category: "storage",
    description: "Microsoft cloud file storage.",
    capabilities: ["File sync", "Shared folders"],
    permissions: ["Read files", "Share files"],
    usedBySpecialists: ["Customer Service Specialist"],
    usedByTeams: [],
    requiredFor: ["Microsoft document workflows"],
    relatedConnectors: ["outlook"],
    recommendedWorkflows: ["File sharing automation"],
    provider: "Microsoft",
    mockProvider: false,
    logoColor: "#0078D4",
    logoInitials: "OD",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "storage",
    description: "Cloud storage for team documents.",
    capabilities: ["File access", "Folder sync"],
    permissions: ["Read files"],
    usedBySpecialists: [],
    usedByTeams: [],
    requiredFor: ["Dropbox-based file workflows"],
    relatedConnectors: [],
    recommendedWorkflows: ["Document backup"],
    provider: "Dropbox",
    mockProvider: false,
    logoColor: "#0061FF",
    logoInitials: "DB",
  },
  {
    id: "instagram",
    name: "Instagram",
    category: "social",
    description: "Direct messages and social engagement.",
    capabilities: ["DM routing", "Comment monitoring"],
    permissions: ["Read messages", "Send replies"],
    usedBySpecialists: ["Marketing Specialist", "Customer Service Specialist"],
    usedByTeams: ["Retail Team"],
    requiredFor: ["Instagram DM support"],
    relatedConnectors: ["facebook"],
    recommendedWorkflows: ["DM triage", "Lead capture from DMs"],
    provider: "Meta",
    mockProvider: false,
    logoColor: "#E4405F",
    logoInitials: "IG",
  },
  {
    id: "facebook",
    name: "Facebook",
    category: "social",
    description: "Page messaging and social customer engagement.",
    capabilities: ["Messenger routing", "Page notifications"],
    permissions: ["Read messages", "Send replies"],
    usedBySpecialists: ["Marketing Specialist"],
    usedByTeams: ["Retail Team"],
    requiredFor: ["Facebook Messenger support"],
    relatedConnectors: ["instagram"],
    recommendedWorkflows: ["Messenger auto-reply"],
    provider: "Meta",
    mockProvider: false,
    logoColor: "#1877F2",
    logoInitials: "FB",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    category: "social",
    description: "Professional networking and B2B outreach.",
    capabilities: ["Message monitoring", "Lead engagement"],
    permissions: ["Read messages"],
    usedBySpecialists: ["Sales Specialist", "Marketing Specialist"],
    usedByTeams: [],
    requiredFor: ["B2B outreach"],
    relatedConnectors: ["hubspot"],
    recommendedWorkflows: ["Lead follow-up"],
    provider: "LinkedIn",
    mockProvider: false,
    logoColor: "#0A66C2",
    logoInitials: "LI",
  },
  {
    id: "tiktok",
    name: "TikTok",
    category: "social",
    description: "Social engagement and brand messaging.",
    capabilities: ["Comment monitoring"],
    permissions: ["Read comments"],
    usedBySpecialists: ["Marketing Specialist"],
    usedByTeams: [],
    requiredFor: ["TikTok engagement workflows"],
    relatedConnectors: ["instagram"],
    recommendedWorkflows: ["Comment triage"],
    provider: "TikTok",
    mockProvider: false,
    logoColor: "#010101",
    logoInitials: "TT",
  },
  {
    id: "zapier",
    name: "Zapier",
    category: "future",
    description: "Automation bridge for future workflow expansion.",
    capabilities: ["Cross-app triggers"],
    permissions: ["Manage zaps"],
    usedBySpecialists: ["Workflow Specialist"],
    usedByTeams: [],
    requiredFor: ["Advanced automation"],
    relatedConnectors: [],
    recommendedWorkflows: ["Cross-platform automation"],
    provider: "Zapier",
    mockProvider: false,
    logoColor: "#FF4A00",
    logoInitials: "ZP",
  },
  {
    id: "make",
    name: "Make",
    category: "future",
    description: "Visual automation for complex workflows.",
    capabilities: ["Scenario triggers"],
    permissions: ["Manage scenarios"],
    usedBySpecialists: ["Workflow Specialist"],
    usedByTeams: [],
    requiredFor: ["Complex automation"],
    relatedConnectors: [],
    recommendedWorkflows: ["Multi-step automation"],
    provider: "Make",
    mockProvider: false,
    logoColor: "#6D00CC",
    logoInitials: "MK",
  },
  {
    id: "shopify",
    name: "Shopify",
    category: "future",
    description: "E-commerce platform integration.",
    capabilities: ["Order sync", "Customer updates"],
    permissions: ["Read orders", "View customers"],
    usedBySpecialists: ["Customer Service Specialist", "Inventory Specialist"],
    usedByTeams: ["Retail Team"],
    requiredFor: ["E-commerce workflows"],
    relatedConnectors: ["stripe", "instagram"],
    recommendedWorkflows: ["Order notifications"],
    provider: "Shopify",
    mockProvider: false,
    logoColor: "#96BF48",
    logoInitials: "SH",
  },
];

export function getConnectorById(id: string): ConnectorCatalogItem | undefined {
  return connectorCatalog.find((connector) => connector.id === id);
}

export function getConnectorsByCategory(category: ConnectorCatalogItem["category"]) {
  return connectorCatalog.filter((connector) => connector.category === category);
}

export const connectorCategories: ConnectorCatalogItem["category"][] = [
  "communication",
  "scheduling",
  "payments",
  "crm",
  "accounting",
  "development",
  "storage",
  "social",
  "future",
];

export const DEFAULT_CONNECTED_IDS = [
  "gmail",
  "google-calendar",
  "stripe",
  "whatsapp",
  "github",
  "vercel",
];

export const DEFAULT_SYNCING_IDS = ["hubspot"];
