import type {
  ActivityItem,
  AIRecommendation,
  AnalyticsSnapshot,
  AnalyticsTimeSeries,
  AuditEntry,
  ConnectorApp,
  Conversation,
  ExecutiveKPIs,
  OnboardingSnapshot,
  SystemHealthSnapshot,
  TeamNode,
  TimelineEvent,
  WorkItem,
  WorkflowStreamEvent,
  WorkforceMember,
} from "@/lib/neo/types";

export function createInitialNeoState() {
  const workforce: WorkforceMember[] = [
    {
      id: "wf-ops-01",
      name: "Ava Chen",
      role: "team_leader",
      title: "Operations Team Lead",
      teamId: "team-ops",
      status: "active",
      liveStatus: "working",
      currentTask: "Review connector health alerts",
      currentAssignment: "wi-103",
      queueSize: 2,
      performanceScore: 94,
      tasksCompletedToday: 11,
      avgResponseMinutes: 4.2,
      avatarInitials: "AC",
    },
    {
      id: "wf-ops-02",
      name: "Marcus Reid",
      role: "manager",
      title: "Workflow Manager",
      teamId: "team-ops",
      status: "busy",
      liveStatus: "waiting",
      currentTask: "Approve onboarding stage 3",
      currentAssignment: "wi-102",
      queueSize: 4,
      performanceScore: 88,
      tasksCompletedToday: 8,
      avgResponseMinutes: 6.1,
      avatarInitials: "MR",
    },
    {
      id: "wf-ops-03",
      name: "Sofia Nwosu",
      role: "specialist",
      title: "Connector Specialist",
      teamId: "team-integrations",
      status: "active",
      liveStatus: "working",
      currentTask: "Sync HubSpot permissions",
      currentAssignment: "wi-102",
      queueSize: 1,
      performanceScore: 91,
      tasksCompletedToday: 14,
      avgResponseMinutes: 3.8,
      avatarInitials: "SN",
    },
    {
      id: "wf-ops-04",
      name: "Eli Park",
      role: "specialist",
      title: "Communications Specialist",
      teamId: "team-comms",
      status: "idle",
      liveStatus: "idle",
      queueSize: 3,
      performanceScore: 86,
      tasksCompletedToday: 9,
      avgResponseMinutes: 5.4,
      avatarInitials: "EP",
    },
    {
      id: "wf-ops-05",
      name: "Jordan Blake",
      role: "specialist",
      title: "Finance Specialist",
      teamId: "team-finance",
      status: "busy",
      liveStatus: "escalated",
      currentTask: "Reconcile QuickBooks sync errors",
      currentAssignment: "wi-104",
      queueSize: 6,
      performanceScore: 79,
      tasksCompletedToday: 5,
      avgResponseMinutes: 12.3,
      avatarInitials: "JB",
    },
    {
      id: "wf-ops-06",
      name: "Riley Santos",
      role: "manager",
      title: "Customer Service Manager",
      teamId: "team-comms",
      status: "active",
      liveStatus: "working",
      currentTask: "Monitor SLA breaches",
      queueSize: 2,
      performanceScore: 92,
      tasksCompletedToday: 7,
      avgResponseMinutes: 4.9,
      avatarInitials: "RS",
    },
  ];

  const teamHierarchy: TeamNode[] = [
    {
      id: "team-ops",
      name: "Operations",
      leadId: "wf-ops-01",
      memberIds: ["wf-ops-01", "wf-ops-02"],
      childTeamIds: ["team-integrations", "team-comms", "team-finance"],
    },
    {
      id: "team-integrations",
      name: "Integrations",
      leadId: "wf-ops-03",
      memberIds: ["wf-ops-03"],
      childTeamIds: [],
    },
    {
      id: "team-comms",
      name: "Communications",
      memberIds: ["wf-ops-04", "wf-ops-06"],
      childTeamIds: [],
    },
    {
      id: "team-finance",
      name: "Finance",
      memberIds: ["wf-ops-05"],
      childTeamIds: [],
    },
  ];

  const connectedConnectors: ConnectorApp[] = [
    {
      id: "hubspot",
      name: "HubSpot",
      category: "CRM",
      connected: true,
      lifecycle: "healthy",
      health: "healthy",
      lastSyncAt: new Date(Date.now() - 120000).toISOString(),
      permissions: ["contacts.read", "deals.read", "workflows.write"],
      oauthStatus: "valid",
      refreshTokenAgeDays: 12,
      usagePercent: 68,
    },
    {
      id: "slack",
      name: "Slack",
      category: "Collaboration",
      connected: true,
      lifecycle: "connected",
      health: "healthy",
      lastSyncAt: new Date(Date.now() - 300000).toISOString(),
      permissions: ["channels.read", "messages.write"],
      oauthStatus: "valid",
      refreshTokenAgeDays: 45,
      usagePercent: 82,
    },
    {
      id: "google-workspace",
      name: "Google Workspace",
      category: "Productivity",
      connected: true,
      lifecycle: "syncing",
      health: "degraded",
      lastSyncAt: new Date(Date.now() - 3600000).toISOString(),
      permissions: ["calendar.read", "gmail.read"],
      oauthStatus: "expiring",
      refreshTokenAgeDays: 89,
      usagePercent: 54,
    },
    {
      id: "quickbooks",
      name: "QuickBooks",
      category: "Finance",
      connected: true,
      lifecycle: "error",
      health: "critical",
      lastSyncAt: new Date(Date.now() - 7200000).toISOString(),
      permissions: ["invoices.read"],
      oauthStatus: "expired",
      refreshTokenAgeDays: 120,
      usagePercent: 31,
      errorMessage: "OAuth token expired — reconnect required",
    },
  ];

  const availableConnectors: ConnectorApp[] = [
    {
      id: "salesforce",
      name: "Salesforce",
      category: "CRM",
      connected: false,
      lifecycle: "authorization_required",
      health: "unknown",
      permissions: [],
      oauthStatus: "missing",
      refreshTokenAgeDays: 0,
      usagePercent: 0,
    },
    {
      id: "whatsapp-business",
      name: "WhatsApp Business",
      category: "Messaging",
      connected: false,
      lifecycle: "connecting",
      health: "unknown",
      permissions: [],
      oauthStatus: "missing",
      refreshTokenAgeDays: 0,
      usagePercent: 0,
    },
    {
      id: "telegram",
      name: "Telegram",
      category: "Messaging",
      connected: false,
      lifecycle: "authorization_required",
      health: "unknown",
      permissions: [],
      oauthStatus: "missing",
      refreshTokenAgeDays: 0,
      usagePercent: 0,
    },
  ];

  const workItems: WorkItem[] = [
    {
      id: "wi-101",
      title: "Onboard Acme Corp messaging channels",
      status: "running",
      assigneeId: "wf-ops-04",
      priority: "high",
      updatedAt: new Date(Date.now() - 600000).toISOString(),
      workflowId: "wf-flow-01",
    },
    {
      id: "wi-102",
      title: "Renew HubSpot OAuth scopes",
      status: "waiting_approval",
      assigneeId: "wf-ops-03",
      priority: "medium",
      updatedAt: new Date(Date.now() - 900000).toISOString(),
      workflowId: "wf-flow-02",
    },
    {
      id: "wi-103",
      title: "Escalation: Google Workspace sync delay",
      status: "escalated",
      assigneeId: "wf-ops-01",
      priority: "urgent",
      updatedAt: new Date(Date.now() - 1800000).toISOString(),
      workflowId: "wf-flow-03",
    },
    {
      id: "wi-104",
      title: "QuickBooks reconciliation backlog",
      status: "escalated",
      assigneeId: "wf-ops-05",
      priority: "urgent",
      updatedAt: new Date(Date.now() - 2400000).toISOString(),
      workflowId: "wf-flow-04",
    },
    {
      id: "wi-105",
      title: "Customer onboarding workflow — Meridian LLC",
      status: "active",
      assigneeId: "wf-ops-02",
      priority: "high",
      updatedAt: new Date(Date.now() - 300000).toISOString(),
      workflowId: "wf-flow-05",
    },
  ];

  const workflowEvents: WorkflowStreamEvent[] = [
    {
      id: "wse-1",
      workItemId: "wi-101",
      label: "Workflow started",
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      actor: "NEO Work Items",
      kind: "started",
    },
    {
      id: "wse-2",
      workItemId: "wi-101",
      label: "Assigned to Communications Specialist",
      timestamp: new Date(Date.now() - 6900000).toISOString(),
      actor: "Ava Chen",
      kind: "progress",
    },
    {
      id: "wse-3",
      workItemId: "wi-102",
      label: "Approval requested",
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      actor: "Marcus Reid",
      kind: "approval",
    },
    {
      id: "wse-4",
      workItemId: "wi-103",
      label: "Escalated to Team Lead",
      timestamp: new Date(Date.now() - 1800000).toISOString(),
      actor: "System",
      kind: "escalation",
    },
    {
      id: "wse-5",
      workItemId: "wi-104",
      label: "Finance queue overloaded",
      timestamp: new Date(Date.now() - 1200000).toISOString(),
      actor: "NEO Workforce",
      kind: "escalation",
    },
  ];

  const conversations: Conversation[] = [
    {
      id: "conv-1",
      channel: "whatsapp",
      customer: { id: "cust-1", name: "Sarah Kim", company: "Acme Corp", tier: "Growth" },
      assignedSpecialistId: "wf-ops-04",
      status: "open",
      sentiment: "positive",
      slaMinutesRemaining: 18,
      slaBreached: false,
      linkedWorkflowId: "wf-flow-01",
      subject: "Onboarding timeline",
      preview: "Can we enable WhatsApp this week?",
      receivedAt: new Date(Date.now() - 300000).toISOString(),
      unread: true,
    },
    {
      id: "conv-2",
      channel: "email",
      customer: { id: "cust-2", name: "David Ortiz", company: "Meridian LLC", tier: "Enterprise" },
      assignedSpecialistId: "wf-ops-06",
      status: "waiting",
      sentiment: "neutral",
      slaMinutesRemaining: 42,
      slaBreached: false,
      linkedWorkflowId: "wf-flow-05",
      subject: "Contract review timeline",
      preview: "When can we expect the onboarding workflow to go live?",
      receivedAt: new Date(Date.now() - 900000).toISOString(),
      unread: true,
    },
    {
      id: "conv-3",
      channel: "instagram",
      customer: { id: "cust-3", name: "Lena Wu", company: "Bright Path Co", tier: "Starter" },
      assignedSpecialistId: "wf-ops-04",
      status: "open",
      sentiment: "positive",
      slaMinutesRemaining: 55,
      slaBreached: false,
      subject: "DM inquiry",
      preview: "Do you integrate with TikTok shop?",
      receivedAt: new Date(Date.now() - 1200000).toISOString(),
      unread: false,
    },
    {
      id: "conv-4",
      channel: "messenger",
      customer: { id: "cust-4", name: "Tom Bradley", company: "Northline HVAC", tier: "Growth" },
      status: "escalated",
      sentiment: "negative",
      slaMinutesRemaining: -12,
      slaBreached: true,
      linkedWorkflowId: "wf-flow-03",
      subject: "Sync issues",
      preview: "Google calendar still not syncing after 2 days",
      receivedAt: new Date(Date.now() - 5400000).toISOString(),
      unread: true,
    },
    {
      id: "conv-5",
      channel: "sms",
      customer: { id: "cust-5", name: "Priya Nair", company: "Summit Legal", tier: "Enterprise" },
      assignedSpecialistId: "wf-ops-06",
      status: "open",
      sentiment: "neutral",
      slaMinutesRemaining: 25,
      slaBreached: false,
      subject: "SMS follow-up",
      preview: "Please confirm the connector permissions list",
      receivedAt: new Date(Date.now() - 600000).toISOString(),
      unread: true,
    },
    {
      id: "conv-6",
      channel: "telegram",
      customer: { id: "cust-6", name: "Alex Rivera", company: "Rivera Logistics", tier: "Growth" },
      assignedSpecialistId: "wf-ops-04",
      status: "resolved",
      sentiment: "positive",
      slaMinutesRemaining: 0,
      slaBreached: false,
      subject: "Bot setup complete",
      preview: "Thanks — automation is working now",
      receivedAt: new Date(Date.now() - 14400000).toISOString(),
      unread: false,
    },
    {
      id: "conv-7",
      channel: "tiktok",
      customer: { id: "cust-7", name: "Mia Chen", company: "Glow Retail", tier: "Starter" },
      status: "open",
      sentiment: "positive",
      slaMinutesRemaining: 70,
      slaBreached: false,
      subject: "TikTok lead",
      preview: "Interested in digital workforce for social commerce",
      receivedAt: new Date(Date.now() - 1800000).toISOString(),
      unread: true,
    },
    {
      id: "conv-8",
      channel: "webchat",
      customer: { id: "cust-8", name: "Chris Doyle", company: "Doyle Dental", tier: "Growth" },
      assignedSpecialistId: "wf-ops-06",
      status: "waiting",
      sentiment: "neutral",
      slaMinutesRemaining: 8,
      slaBreached: false,
      subject: "Live chat",
      preview: "Why is customer service queue backed up?",
      receivedAt: new Date(Date.now() - 120000).toISOString(),
      unread: true,
    },
  ];

  const onboarding: OnboardingSnapshot = {
    readinessScore: 72,
    targetScore: 100,
    stage: "Connector setup",
    businessDiscoveryComplete: true,
    launchReadiness: "almost_ready",
    missingRequirements: [
      "Enable WhatsApp Business messaging",
      "Launch first automated workflow",
      "Reconnect QuickBooks OAuth",
    ],
    estimatedSetupHours: 6,
    checklist: [
      { id: "ob-1", label: "Complete business profile", completed: true, required: true },
      { id: "ob-2", label: "Assign operations team lead", completed: true, required: true },
      { id: "ob-3", label: "Connect primary CRM", completed: true, required: true },
      { id: "ob-4", label: "Enable messaging channels", completed: false, required: true },
      { id: "ob-5", label: "Launch first workflow", completed: false, required: true },
      { id: "ob-6", label: "Review AI recommendations", completed: false, required: false },
    ],
    recommendedConnectorIds: ["whatsapp-business", "salesforce"],
    recommendedSpecialistIds: ["wf-ops-03", "wf-ops-04"],
  };

  const executive: ExecutiveKPIs = {
    businessHealthScore: 82,
    level: "healthy",
    summary: "Operations stable with one degraded connector and Finance escalated.",
    activeSpecialists: workforce.filter((m) => m.role === "specialist" && m.liveStatus === "working").length,
    activeManagers: workforce.filter((m) => m.role === "manager" && m.liveStatus !== "offline").length,
    runningWorkflows: workItems.filter((w) => w.status === "running" || w.status === "active").length,
    waitingApprovals: workItems.filter((w) => w.status === "waiting_approval").length,
    connectedIntegrations: connectedConnectors.filter((c) => c.connected).length,
    openConversations: conversations.filter((c) => c.status !== "resolved").length,
    revenueMtdUsd: 284500,
    revenueTrendPercent: 12.4,
  };

  const analytics: AnalyticsSnapshot = {
    workforceUtilization: 78,
    connectorUptime: 96.4,
    automationsRun: 142,
    customerSatisfaction: 4.6,
    costSavingsUsd: 12400,
    hoursSaved: 186,
    workflowsPerDay: 34,
    automationPercent: 62,
    avgResponseMinutes: 5.2,
    tasksCompleted: 287,
    conversationVolume: 156,
  };

  const analyticsSeries: AnalyticsTimeSeries = {
    workflowsPerDay: [
      { label: "Mon", value: 28 },
      { label: "Tue", value: 31 },
      { label: "Wed", value: 29 },
      { label: "Thu", value: 34 },
      { label: "Fri", value: 36 },
      { label: "Sat", value: 18 },
      { label: "Sun", value: 14 },
    ],
    conversationVolume: [
      { label: "Mon", value: 120 },
      { label: "Tue", value: 138 },
      { label: "Wed", value: 145 },
      { label: "Thu", value: 156 },
      { label: "Fri", value: 162 },
      { label: "Sat", value: 74 },
      { label: "Sun", value: 58 },
    ],
    specialistUtilization: [
      { label: "Mon", value: 72 },
      { label: "Tue", value: 75 },
      { label: "Wed", value: 78 },
      { label: "Thu", value: 81 },
      { label: "Fri", value: 78 },
      { label: "Sat", value: 45 },
      { label: "Sun", value: 38 },
    ],
    connectorHealth: [
      { label: "Mon", value: 98 },
      { label: "Tue", value: 97 },
      { label: "Wed", value: 96 },
      { label: "Thu", value: 96 },
      { label: "Fri", value: 94 },
      { label: "Sat", value: 99 },
      { label: "Sun", value: 99 },
    ],
  };

  const activity: ActivityItem[] = [
    {
      id: "act-1",
      label: "HubSpot sync completed",
      timestamp: new Date(Date.now() - 120000).toISOString(),
      type: "connector",
    },
    {
      id: "act-2",
      label: "Workflow approval requested",
      timestamp: new Date(Date.now() - 900000).toISOString(),
      type: "workflow",
    },
    {
      id: "act-3",
      label: "New WhatsApp conversation — Acme Corp",
      timestamp: new Date(Date.now() - 300000).toISOString(),
      type: "messaging",
    },
    {
      id: "act-4",
      label: "Finance Specialist escalated wi-104",
      timestamp: new Date(Date.now() - 1200000).toISOString(),
      type: "workforce",
    },
  ];

  const recommendations: AIRecommendation[] = [
    {
      id: "rec-1",
      title: "Enable WhatsApp Business connector",
      summary: "3 onboarding blockers relate to messaging channel gaps.",
      priority: "high",
      category: "onboarding",
    },
    {
      id: "rec-2",
      title: "Reconnect QuickBooks OAuth",
      summary: "Finance queue is overloaded due to expired connector token.",
      priority: "high",
      category: "connectors",
    },
    {
      id: "rec-3",
      title: "Hire Marketing Specialist",
      summary: "Social channel volume up 24% — capacity gap detected.",
      priority: "medium",
      category: "workforce",
    },
  ];

  const systemHealth: SystemHealthSnapshot = {
    platform: "healthy",
    connectors: "degraded",
    workforce: "healthy",
    messaging: "healthy",
    lastCheckedAt: new Date().toISOString(),
  };

  const audit: AuditEntry[] = [
    {
      id: "au-1",
      action: "connector.permission.updated",
      actor: "Sofia Nwosu",
      timestamp: new Date(Date.now() - 600000).toISOString(),
      detail: "HubSpot workflows.write granted",
    },
    {
      id: "au-2",
      action: "workflow.approval.requested",
      actor: "Marcus Reid",
      timestamp: new Date(Date.now() - 900000).toISOString(),
      detail: "wi-102 awaiting manager approval",
    },
  ];

  const timeline: TimelineEvent[] = [
    {
      id: "tl-1",
      label: "Work item created",
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      actor: "System",
    },
    {
      id: "tl-2",
      label: "Assigned to Communications Specialist",
      timestamp: new Date(Date.now() - 6900000).toISOString(),
      actor: "Ava Chen",
    },
    {
      id: "tl-3",
      label: "Connector health check passed",
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      actor: "NEO Connector Platform",
    },
  ];

  return {
    workforce,
    teamHierarchy,
    connectedConnectors,
    availableConnectors,
    workItems,
    workflowEvents,
    conversations,
    onboarding,
    executive,
    analytics,
    analyticsSeries,
    activity,
    recommendations,
    systemHealth,
    audit,
    timeline,
  };
}

export type NeoPlatformState = ReturnType<typeof createInitialNeoState>;
